apps/game_features/urls.py
from django.conf.urls import url
from django.urls import path, reverse_lazy
from apps.game_features import views


app_name = 'game_features'

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("participacao/criar/", views.complaint_add_view, name="complaint_add"),
    path("participacao/detalhe/<participacao_slug>", views.complaint_detail_view, name="complaint_detail"),
    path("participacao/detalhe/aluno/<aluno_id>", views.complaints_aluno_view, name="complaints_aluno"),
    path("participacao/detalhe/turma/<turma_id>", views.complaints_turma_list_view, name="complaints_turma_list"),
    path("participacao/acao/criar/<complaint_id>", views.parecer_dt_add_view, name="parecer_dt_add"),
    path("ajax/load-alunos/", views.load_alunos_da_turma, name="ajax_load_alunos"),
    path("ajax/load-numero-aluno/", views.load_numero_do_aluno, name="ajax_load_numero_aluno"),
]

game_app_main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('contas/', include('apps.accounts.urls')),
    path('game/', include('apps.game_features.urls')),
]

apps/game_features/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from apps.accounts.models import User, Student, Teacher
from apps.school_structure.models import SchoolClass


class Complaint(models.Model):
    """ Um modelo para as participações disciplinares """

    # identificação
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    QUALIDADE_CHOICES = (
        ('A', 'Aluno'),
        ('F', 'Funcionário'),
        ('P', 'Professor'),
    )
    qualidade = models.CharField(
        'qualidade',
        choices=QUALIDADE_CHOICES,
        max_length=100,
        default='P',
    )
    slug = models.SlugField(
        max_length=50,
        unique=True,
        blank=True,
        help_text="Deixar em branco para criar um slug automático e único",
    )

    turma = models.ForeignKey(
        SchoolClass,
        related_name='turma',
        on_delete=models.CASCADE
    )
    dt = models.ForeignKey(
        Teacher,
        related_name='DT',
        on_delete=models.CASCADE
    )

    class_number = models.CharField(
        "Número",
        max_length=200,
    )
    aluno = models.ForeignKey(
        Student,
        related_name='aluno',
        on_delete=models.CASCADE
    )
    local = models.CharField(
        "Local da ocorrência",
        max_length=200,
    )
    hora = models.TimeField(
        "Hora da ocorrência",
    )
    dia = models.DateField(
        'Dia da ocorrência',
    )

    # comportamentos incorretos
    comer = models.BooleanField(
        'Comer na sala de aula.',
        default=False,
    )
    levantar = models.BooleanField(
        'Levantar-se durante a aula sem autorização.',
        default=False,
    )
    conversar = models.BooleanField(
        'Perturbar a aula com conversa e brincadeira.',
        default=False,
    )
    entradar_sair_desordeira = models.BooleanField(
        'Entrar/sair da aula de forma desordeira.',
        default=False,
    )
    patrimonio = models.BooleanField(
        'Não respeitar o património escolar.',
        default=False,
    )
    recolher_imagens = models.BooleanField(
        'Recolher/divulgar imagens/sons sem autorização.',
        default=False,
    )
    fumar = models.BooleanField(
        'Fumar dentro do recinto escolar.',
        default=False,
    )
    regras_espaços = models.BooleanField(
        'Não cumprir as regras de utilização dos diversos espaços.',
        default=False,
    )
    aparelhos_eletronicos = models.BooleanField(
        'Utilizar indevidamente o telemóvel ou outro aparelho eletrónico.',
        default=False,
    )
    linguagem = models.BooleanField(
        'Utilizar linguagem imprópria.',
        default=False,
    )
    ofender_colegas = models.BooleanField(
        'Ofender verbalmente os colegas.',
        default=False,
    )
    ameacar = models.BooleanField(
        'Ameaçar/intimidar colegas.',
        default=False,
    )
    recusar_trabalhar = models.BooleanField(
        'Recusar-se a trabalhar.',
        default=False,
    )
    abandonar_aula = models.BooleanField(
        'Abandonar a aula sem autorização do professor.',
        default=False,
    )
    Ofender_prof_fun = models.BooleanField(
        'Ofender verbalmente professores/funcionários.',
        default=False,
    )
    roubar = models.BooleanField(
        'Roubar/furtar.',
        default=False,
    )
    nao_obedecer = models.BooleanField(
        'Não obedecer às indicações do adulto.',
        default=False,
    )
    agredir = models.BooleanField(
        'Agredir.',
        default=False,
    )
    contextualizacao = models.TextField(
        'Breve descrição/contextualização do(s) comportamento(s) incorreto(s):',
        blank=True,
    )

    # campos de informação complementar
    ATIVIDADE_CHOICES = (
        ('EM', 'em atividade letiva'),
        ('FORA', 'fora de atividade letiva'),
    )
    atividade = models.CharField(
        'Tipo de atividade',
        choices=ATIVIDADE_CHOICES,
        max_length=50,
        default='EM',
    )
    ordem_saida = models.BooleanField(
        'Dada ordem de saída da sala de aula',
        default=False,
    )
    falta = models.BooleanField(
        'Marcada falta',
        default=False,
    )
    tarefa = models.TextField(
        'Encaminhamento com a tarefa:',
        blank=True,
    )
    ESTADO_CHOICES = (
        ('ANALISE', 'Em análise'),
        ('ARQUIVADA', 'Arquivada'),
        ('CONCLUIDA', 'Participação disciplinar registada'),
        ('PROCEDIMENTO', 'Procedimento Disciplinar Sumário'),
        ('EMD', 'Procedimento Disciplinar - EMD'),
    )
    estado = models.CharField(
        'Estado',
        choices=ESTADO_CHOICES,
        max_length=100,
        default='ANALISE',
    )
    parecer_dt = models.BooleanField(
        'Participação com parecer do DT',
        default=False,
    )
    created = models.DateTimeField(
        'Criado em',
        auto_now_add=True
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now=True
    )

    class Meta:
        """options (metadata) to the field"""
        verbose_name = "Participação disciplinar"
        verbose_name_plural = "Participações disciplinares"
        ordering = ['user']

    def __str__(self):
        """Return the str.name fom the object"""
        return self.user.name

    def get_absolute_url(self):
        return reverse(
            'game_features:complaint_detail',
            kwargs={'participacao_slug': self.slug}
        )

    def save(self, *args, **kwargs):
        """ Set automatic and unique slug from turma, numero e id filed"""
        super(Complaint, self).save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(self.turma) + str(self.class_number) + "_" + str(self.id)
            self.save()

# fazer drop nesta tabela
# https://stackoverflow.com/questions/54256136/how-to-drop-a-table-sqlite3-in-django-2-1

# corrigir erros da tabela --- ver este link -> answered Feb 17, 2020 at 20:49
# Ashish Gupta
# https://stackoverflow.com/questions/34548768/no-such-table-exception

# procedimento
# 1 - abrir o executavel "sqlite3.exe" na pasta do projeto
# 2 - correr o comando para abrir a base de dados
#     .open db.sqlite3
# 3 - ver tabelas
#     .table
# 4 - apagar esta tabela
#     DROP TABLE game_features_complaint;
# 5 - apagar migrações da app
# 6 - correr python manage.py makemigrations
# 7 - Follow this steps to get fixed this issue.
#
# python manage.py migrate --fake APPNAME zero
# This will make your migration to fake. Now you can run the migrate script
#
# python manage.py migrate APPNAME
# OR
# python manage.py migrate
# Tables will be created and you solved your problem.. Cheers!!!


class ParecerDT(models.Model):
    """ Um modelo para as ações dos DTs nas participações disciplinares """

    # identificação

    slug = models.SlugField(
        max_length=50,
        unique=True,
        blank=True,
        help_text="Deixar em branco para criar um slug automático e único",
    )
    dt = models.ForeignKey(
        Teacher,
        related_name='DiretorTurma',
        on_delete=models.CASCADE
    )
    complaint = models.ForeignKey(
        Complaint,
        related_name='participacao',
        on_delete=models.CASCADE
    )

    PARECER_CHOICES = (
        ('1', 'Participação arquivada e sem efeito.'),
        ('2', 'Ocorrência não frequente e não grave.'),
        ('3', 'Procedimento disciplinar sumário.'),
        ('4', 'Procedimento disciplinar sumário - Equipa EMD.'),
    )
    parecer = models.CharField(
        'Parecer do DT',
        choices=PARECER_CHOICES,
        max_length=250,
        default='F',
    )

    # ações DT
    advertencia_verbal_aluno = models.BooleanField(
        'Advertência verbal ao aluno.',
        default=False,
    )
    comunicacao_EE = models.BooleanField(
        'Comunicação ao Encarregado de Educação.',
        default=False,
    )
    descricao_acao_dt = models.TextField(
        'Breve descrição da(s) ações(s) tomadas(s) pelo DT:',
        blank=True,
    )
    created = models.DateTimeField(
        'Criado em',
        auto_now_add=True
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now=True
    )

    class Meta:
        """options (metadata) to the field"""
        verbose_name = "Parecer do DT"
        verbose_name_plural = "Pareceres dos DT's"
        ordering = ['created']

    def __str__(self):
        """Return the str.name fom the object"""
        return self.dt.name

    def save(self, *args, **kwargs):
        """ Set automatic and unique slug from turma, numero e id filed"""
        super(ParecerDT, self).save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(self.complaint.slug) + "-" + str(self.id)
            self.save()

apps/game_features/forms.py
from django import forms
from django.forms.models import ModelChoiceField

from .models import Complaint, ParecerDT
from apps.school_structure.models import SchoolClass


# create a ModelForm
class ComplaintAddForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ComplaintAddForm, self).__init__(*args, **kwargs)
        self.fields['user'].disabled = True

    class Meta:
        model = Complaint
        fields = "__all__"


class ComplaintAddFormManual(forms.ModelForm):

    class Meta:
        model = Complaint
        exclude = ['user', 'qualidade', 'dt', 'estado', 'slug', 'parecer_dt']
        widgets = {
            'dia': forms.DateInput(
                format='%Y-%m-%d',
                attrs={
                    'type': 'date',
                },
            ),
            'hora': forms.TimeInput(
                format='%H:%M',
                attrs={
                    'type': 'time',
                },
            ),
        }


class ParecerAddForm(forms.ModelForm):

    class Meta:
        model = ParecerDT
        exclude = ['dt', 'complaint', 'slug']

templates/game_features/alunos_dropdown_list_options.html
<option value=""> Selecione... </option>

{% for aluno in alunos %}
    <option value="{{ aluno.pk }}">{{ aluno }}</option>
{% endfor %}

templates/game_features/complaints_aluno_list.html
{% extends 'game_app_main/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Participações Disciplinares</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item">
                                <a href="{% url 'game_features:homepage' %}">
                                    Home
                                </a>
                            </li>
                            <li class="breadcrumb-item active">Participações aluno</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <div class="content">

            <div class="row">
                <div class="col-12">
                    <div class="card card-indigo">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-4">
                                    <label>Aluno: </label>
                                    {{ aluno.name }}
                                </div>
                                <div class="col-sm-2">
                                    <label>Turma: </label>
                                    {{ aluno.studentmore.school_class }}
                                </div>
                                <div class="col-sm-2">
                                    <label>Número: </label>
                                    {{ aluno.studentmore.class_number }}
                                </div>
                                <div class="col-sm-4">
                                    <label>Diretor de Turma: </label>
                                    {{ aluno.studentmore.school_class.teacher_dt.get_first_name }}
                                    {{ aluno.studentmore.school_class.teacher_dt.get_last_name }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-3">
                                    <label>Número Interno: </label>
                                    {{ aluno.internal_number }}
                                </div>
                                <div class="col-sm-3">
                                    <label>Data de nascimento: </label>
                                    {{ aluno.birth_date }}
                                </div>
                                <div class="col-sm-2">
                                    <label>idade: </label>
                                    {{ aluno.get_age }}
                                </div>
                                <div class="col-sm-3">
                                    <label>Morada: </label>
                                    {{ aluno.address }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    <label>Encarregado de Educação: </label>
                                    {{ aluno.studentmore.name_ee }}
                                </div>
                                <div class="col-sm-4">
                                    <label>email EE: </label>
                                    {{ aluno.studentmore.email_ee }}
                                </div>
                                <div class="col-sm-4">
                                    <label>Telefone: </label>
                                    {{ aluno.studentmore.phone_ee }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            {% if complaints_aluno %}
                <div class="row">
                <div class="col-12">
                <div class="card card-indigo">
                    <div class="card-header">
                        <h3 class="card-title">Todas as participações do {{ aluno.get_first_name }} &nbsp </h3>
                        <span class="badge bg-gray">{{ complaints_aluno.count }}</span>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>

                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                        <table class="table table-head-fixed text-nowrap">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Denunciante</th>
                                <th>Data da <br> ocorrência</th>
                                <th>Data da <br> participação</th>
                                <th>Estado</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for complaint in complaints_aluno %}
                                <tr>

                                    <td>{{ complaint.id }}</td>
                                    <td>
                                        {{ complaint.user.get_first_name}} {{ complaint.user.get_last_name}}
                                        <br>
                                        ({{ complaint.get_qualidade_display }})
                                    </td>
                                    <td>{{ complaint.dia|date:"d/M/Y" }}</td>
                                    <td>
                                        {{ complaint.created|date:"d/M/Y" }}
                                        <br>
                                        Hora: {{ complaint.created|time:"G:i" }}
                                    </td>
                                    <td>
                                        <h5>
                                            <span
                                                {% if complaint.estado == "ANALISE" %}
                                                    class="badge badge-pill badge-info">
                                                {% elif complaint.estado == "ARQUIVADA" %}
                                                    class="badge badge-pill badge-success">
                                                {% elif complaint.estado == "CONCLUIDA" %}
                                                    class="badge badge-pill badge-warning">
                                                {% else %}
                                                    class="badge badge-pill badge-danger">
                                                {% endif %}
                                                {{ complaint.get_estado_display }}
                                            </span>
                                        </h5>
                                    </td>
                                    <td>
                                        <a href="{{ complaint.get_absolute_url }}">
                                            <i class="fa fa-eye"></i>
                                        </a>
                                        &nbsp
                                        {% if not complaint.parecer_dt and dt_da_turma %}
                                        <a href="{% url 'game_features:parecer_dt_add' complaint.id %}" >
                                            <i class="fa fa-gavel"></i>
                                        </a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer card-gray-dark clearfix">
                    </div>
                </div>
                <!-- /.card -->
            {% endif %}

          </div>
        </div>
        </div>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
{% endblock %}

templates/game_features/complaints_turma_list.html
{% extends 'game_app_main/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Participações Disciplinares</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item">
                                <a href="{% url 'game_features:homepage' %}">
                                    Home
                                </a>
                            </li>
                            <li class="breadcrumb-item active">Participações turma</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <div class="content">

            <div class="row">
                <div class="col-12">
                    <div class="card card-indigo">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <label>Turma: </label>
                                    {{ turma.name }}
                                </div>
                                <div class="col-sm-6">
                                    <label>Diretor de Turma: </label>
                                    {{ turma.teacher_dt.get_first_name }}
                                    {{ turma.teacher_dt.get_last_name }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            {% if complaints_turma %}
                <div class="row">
                <div class="col-12">
                <div class="card card-indigo">
                    <div class="card-header">
                        <h3 class="card-title">Todas as participações da turma {{ turma.name }} &nbsp </h3>
                        <span class="badge bg-gray">{{ complaints_turma.count }}</span>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>

                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                        <table class="table table-head-fixed text-nowrap">
                            <thead>
                            <tr>
                                <th> Id </th>
                                <th> Denunciante </th>
                                <th> Aluno </th>
                                <th> Data da <br> ocorrência </th>
                                <th> Data da <br> participação </th>
                                <th> Estado </th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for complaint in complaints_turma %}
                                <tr>

                                    <td>{{ complaint.id }}</td>
                                    <td>
                                        {{ complaint.user.get_first_name}} {{ complaint.user.get_last_name}}
                                        <br>
                                        ({{ complaint.get_qualidade_display }})
                                    </td>
                                    <td> {{ complaint.aluno}} </td>
                                    <td> {{ complaint.dia|date:"d/M/Y" }} </td>
                                    <td>
                                        {{ complaint.created|date:"d/M/Y" }}
                                        <br>
                                        Hora: {{ complaint.created|time:"G:i" }}
                                    </td>
                                    <td>
                                        <h5>
                                            <span
                                                {% if complaint.estado == "ANALISE" %}
                                                    class="badge badge-pill badge-info">
                                                {% elif complaint.estado == "ARQUIVADA" %}
                                                    class="badge badge-pill badge-success">
                                                {% elif complaint.estado == "CONCLUIDA" %}
                                                    class="badge badge-pill badge-warning">
                                                {% else %}
                                                    class="badge badge-pill badge-danger">
                                                {% endif %}
                                                {{ complaint.get_estado_display }}
                                            </span>
                                        </h5>
                                    </td>
                                    <td>
                                        <a href="{{ complaint.get_absolute_url }}">
                                            <i class="fa fa-eye"></i>
                                        </a>
                                        &nbsp
                                        {% if not complaint.parecer_dt and dt_da_turma %}
                                        <a href="{% url 'game_features:parecer_dt_add' complaint.id %}" >
                                            <i class="fa fa-gavel"></i>
                                        </a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer card-gray-dark clearfix">
                    </div>
                </div>
                <!-- /.card -->
            {% endif %}

          </div>
        </div>
        </div>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
{% endblock %}

templates/game_features/numero_aluno.html
{{ numero_aluno }}