apps/accounts/urls.py
from django.conf.urls import url
from django.urls import path, reverse_lazy
from apps.accounts import views

# utilizado para envio de emails de recuperação de senha
from django.contrib.auth import views as auth_views

app_name = 'contas'

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),

    # change password
    path("change_password/", views.change_password, name="change_password"),

    # reset password with email

]

apps/game_features/urls.py
from django.conf.urls import url
from django.urls import path, reverse_lazy
from apps.game_features import views


app_name = 'game_features'

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("participacao/criar/", views.complaint_add_view, name="complaint_add"),
    path("participacao/detalhe/<participacao_slug>", views.complaint_detail_view, name="complaint_detail"),
    path("participacao/detalhe/aluno/<aluno_id>", views.complaints_aluno_view, name="complaints_aluno"),
    path("participacao/detalhe/turma/<turma_id>", views.complaints_turma_list_view, name="complaints_turma_list"),
    path("participacao/acao/criar/<complaint_id>", views.parecer_dt_add_view, name="parecer_dt_add"),
    path("ajax/load-alunos/", views.load_alunos_da_turma, name="ajax_load_alunos"),
    path("ajax/load-numero-aluno/", views.load_numero_do_aluno, name="ajax_load_numero_aluno"),
]

game_app_main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('contas/', include('apps.accounts.urls')),
    path('game/', include('apps.game_features.urls')),
]

game_app_main/views.py
from django.shortcuts import render
from django.http import HttpResponse


def home(request):
    template_name = 'game_app_main/home.html'
    message = 'Gabinete de Apoio e Mediação Escolar'
    context = {'msn': message}
    return render(request, template_name, context)

templates/game_app_main/base.html
{% load static %}

<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<!-- pt-PT - português de Portugal. -->
<html lang="pt-PT">
<head>
    <!-- character encoding for the HTML document - UTF-8 character set, covers almost all of the characters and symbols -->
    <!-- in the world! -->
    <meta charset="utf-8">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The X-UA-Compatible meta tag allows to choose what version of Internet Explorer the page should be rendered as -->
    <!-- edge mode tells Internet Explorer to display content in the highest mode available -->
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <!-- title tab -->
    <title>GAME</title>


    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'admin_lte/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'admin_lte/dist/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <!-- GAME style -->
    <link rel="stylesheet" href="{% static 'game/css/game.css' %}">

    <!-- game favicon -->
    <link rel="icon" type="image/svg+xml" href="{% static 'game/img/favicon_io/game_favicon.svg ' %}">
    <link rel="icon" type="image/png" href="{% static 'game/img/favicon_io/game_favicon.png ' %}">

    <!-- ToastsR -->
    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'admin_lte/plugins/toastr/toastr.css' %}" media="all">
    <script type="text/javascript" src="{% static 'admin_lte/plugins/toastr/toastr.min.js' %}"></script>

</head>
<body class="layout-top-nav layout-footer-fixed">

<!-- Mensagens do Django -->
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% elif message.tags == 'info' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% elif message.tags == 'warning' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% elif message.tags == 'error' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% endif %}
    {% endfor %}
{% endif %}

<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item d-none d-sm-inline-block">
                <a href="{% url 'game_features:homepage' %}" class="navbar-brand">
                    <img src="{% static 'game/img/game_logo.jpg' %}" alt="game Logo"
                         class="brand-image img-push elevation-3"
                         style="opacity: .8">
                    <span class="brand-text font-weight-light"><strong>Plataforma GAME</strong></span>
                </a>
            </li>

        </ul>
        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            <!-- user -->
            <li class="nav-item">
                <i class="nav-link">
                   Utilizador:<b> {{request.user.get_first_name}} {{ request.user.get_last_name }}</b>
                </i>
            </li>
            <!-- Contact -->
            <li class="nav-item d-none d-sm-inline-block">
                <a href="mailto:game@avalmancil.pt" class="nav-link">
                    <i class="far fa-envelope"></i>
                    &nbsp
                    game@avalmancil.pt
                </a>
            </li>

            <!-- Settings dropdown -->
            <li class="nav-item dropdown show ">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="true">
                    <i class="fas fa-cog"></i>
                </a>
                <div class="dropdown-menu hide" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-5px, 40px, 0px);">
                    <a class="dropdown-item" tabindex="-1" href="{% url 'contas:change_password' %}">Alterar Password</a>
                </div>
            </li>

            <li class="nav-item">
                <a href="{% url 'contas:logout' %}" class="nav-link">Logout</a>
            </li>

            <!-- End Settings dropdown -->
        </ul>
    </nav>
    <!-- /.navbar -->

    {% block sidebar %}



    {% endblock %}


    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        {% block content %}

        {% endblock %}
    </div>
    <!-- /.content-wrapper -->

    {% block footer %}

        {% include 'game_app_main/footer.html' %}

    {% endblock %}
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{% static 'admin_lte/plugins/jquery/jquery.min.js' %}"></script>
<!-- my jQuery -->
<script src="{% static 'myJS/complaint.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'admin_lte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'admin_lte/dist/js/adminlte.min.js' %}"></script>
</body>
</html>

templates/game_app_main/footer.html
{% load static %}

{% block footer %}
    <!-- Main Footer -->
    <footer class="main-footer">
        <!-- To the right -->
        <div class="float-right d-none d-sm-inline">
            Agrupamento de Escolas de Almancil
        </div>
        <!-- Default to the left -->
        {% if user.is_authenticated %}
            <strong>Copyright &copy; 2023 <a href="{% url 'game_features:homepage' %}">GAME</a>.</strong> All rights reserved.
        {% else %}
            <strong>Copyright &copy; 2023 <a href="{% url 'home' %}">GAME</a>.</strong> All rights reserved.
        {% endif %}
    </footer>
{% endblock %}

templates/game_app_main/home.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-PT">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>GAME</title>

    <link rel="icon" href="{% static 'game/img/favicon_io/game_favicon.svg' %}" sizes="any" type="image/svg+xml">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'admin_lte/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'admin_lte/dist/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'game/css/game.css' %}">

    <!-- ToastsR -->
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'admin_lte/plugins/toastr/toastr.css' %}" media="all">
    <script type="text/javascript" src="{% static 'admin_lte/plugins/toastr/toastr.min.js' %}"></script>

</head>
<body class="hold-transition layout-top-nav layout-footer-fixed">

<!-- Mensagens do Django -->
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% elif message.tags == 'info' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% elif message.tags == 'warning' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% elif message.tags == 'error' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% endif %}
    {% endfor %}
{% endif %}

<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
        <div class="container">
            <a href="{% url 'home' %}" class="navbar-brand">
                <img src="{% static 'game/img/game_logo.jpg' %}" alt="game Logo"
                     class="brand-image img-push elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">GAME</span>
            </a>

            <!-- Right navbar links -->
            <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
                <li class="nav-item">
                    <a href="{% url 'contas:login' %}" class="nav-link">Login</a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- /.navbar -->

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container">

            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container">
                <div class="centradinho">
                    <img src="{% static 'game/img/game largo3.png' %}" alt="background image" class="centradinho">
                </div>
                <div class="centrado">

                </div>
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Main Footer -->
    {% block footer %}

        {% include 'game_app_main/footer.html' %}

    {% endblock %}
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{% static 'admin_lte/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'admin_lte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'admin_lte/dist/js/adminlte.min.js' %}"></script>
</body>
</html>